const express = require("express");
const cors = require('cors');
const path = require("path");
const app = express();
const threadRouter = require("./routes/threadRouter");

//allow requests via CORS
app.use(cors());

// Parse incoming JSON request bodies
app.use(express.json());

app.use((req, res, next) => {
  req.requestTime = new Date().toISOString();
  next();
});

app.use("/api/1/threads",threadRouter);

// Serve static assets generated by the client build
app.use(express.static(path.join(__dirname, '..', 'client', 'dist')));

// Fallback route: serve index.html for SPA client-side routing
app.all('/{*splat}', (req, res) => {
  console.log("React app requested");
  res.sendFile(path.join(__dirname, '..', 'client', 'dist', 'index.html'));
});


module.exports = app;